server:
    image: node:5.9
    volumes:
        - ./server/app:/usr/local/src/app
    ports:
        - 3000:3000
    working_dir: /usr/local/src/app
    entrypoint: /usr/local/src/app/entrypoint.sh

nginx:
    image: nginx
    volumes:
        - ./nginx/conf.d/:/etc/nginx/conf.d
        - ./nginx/lgws.access.log:/var/log/nginx/lgws.access.log
        - ./nginx/lgws.error.log:/var/log/nginx/lgws.error.log
    volumes_from:
        - data-client
    links:
        - server
    ports:
        - '8080:80'
        - '443:443'

data-client:
    image: node:5.9
    volumes:
        - ./client/app:/usr/share/nginx/html
        - ./nodejs/shared/.npmrc:/root/.npmrc
    working_dir: /usr/share/nginx/html
    entrypoint: /usr/share/nginx/html/entrypoint.sh
